//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBayInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int ItemID { get; set; }
        public int ItemType { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> EstValue { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual itemtype itemtype1 { get; set; }
    }
}
