//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBayInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class supply
    {
        public int SuppliesID { get; set; }
        public string SupDesc { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> NumInventory { get; set; }
    }
}
